site_name: AI Finance Lab
site_description: Building the next generation of AI-enabled finance professionals
site_url: ""

theme:
  name: material
  logo: assets/4MATR Logo.png
  favicon: assets/4MATR Logo.png

  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html

nav:

  - Home: index.md

  - Start Here:
      - About AI Finance Lab: about.md
      - Learning Roadmap: learning-roadmap.md
      - Self-learning Resources: resources.md
      - Contribute: contribute.md

  - Learn:
    - Finance Foundations:
        - Accounting Fundamentals:
            - Overview: Accounting Fundamentals/learn Accounting fundamentals.md

        - Finance Fundamentals:
            - Overview: Finance Fundamentals/learn FSA fundamentals.md

        - Modelling Fundamentals:
            - Overview: Modelling Fundamentals/learn Modelling fundamentals.md
            - FM Mechanics: Modelling Fundamentals/learn FM mechanics.md
            - DCF Mechanics: Modelling Fundamentals/learn DCF mechanics.md
            - LBO Mechanics: Modelling Fundamentals/learn LBO mechanics.md
            - Merger Mechanics: Modelling Fundamentals/learn Merger mechanics.md

    - AI Foundations:
        - AI Fundamentals:
            - Overview: AI Fundamentals/learn AI Fundamentals.md
            - Prompt Engineering : AI Fundamentals/learn Prompt Engineering.md
            - AI Model Auditing : AI Fundamentals/learn AI Model Auditing.md
            - AI-Assisted Financial Modelling : AI Fundamentals/learn AI Assisted Modelling.md

  # - Financial Modelling:

  #     - Modelling :
  #         - Financial Modelling: learn FM modelling.md
  #         - DCF: learn DCF mechanics.md
  #         - LBO: learn LBO mechanics.md
          # - Merger Modelling: Modelling Fundamentals/learn Merger mechanics.md

  #     - Building Models:
  #         - Financial Model: FM/9. learn FM modelling.md
  #         - DCF Model: DCF/10. learn DCF modelling.md
  #         - LBO Model: LBO/11. learn LBO modelling.md
  #         - Merger Model: Merger/12. learn merger modelling.md

  #     - Best Practices:
  #         - Model Auditing: 2. learn auditing.md
  #         - Model Balancing: 3. learn balancing.md
  #         - Model Formatting: 4. learn formatting.md
  #         - About the Models: about Models.md

  - Case Studies:
      - Breville Group:
          - About the Case Study: Case Study/Breville/about BRG.md
  #         - About the Annual Report: Case Study/Breville/about AR.md
          - Annual Report (PDF): Case Study/Breville/Annual Report/Breville-Annual-Report-2025.pdf
          - YahooFinance Financials Export (XLSX): Case Study/Breville/Data/BRG.AX Financials.xlsx
          - Preliminary AI Assessment: 
            - FM Opinion: Case Study/Breville/Prompt Outputs/prompt FM opinion.md
            - DCF Opinion: Case Study/Breville/Prompt Outputs/prompt DCF opinion.md
            - LBO Strategy: Case Study/Breville/Prompt Outputs/prompt LBO strategy.md
            - Merger Strategy: Case Study/Breville/Prompt Outputs/prompt merger strategy.md
          - AI Model Assessment:
            - Financial Model v1: Case Study/Breville/Models/AI Output/FM/AI FM Assessment v1.md
  
  - 4MATR Resources:
     - AI Finance Handbook:
          - Chapter 1: 4MATR Resources/AI Finance Handbook/Chapter 01.md


  - 4MATR Community:
      - AI Finance Community: 4MATR Community/ai-finance-community.md

  - Newsletter:
      - The 4MATR Brief: Newsletter/newsletter_index.md
      - Issue 0  - Welcome: Newsletter/issue-00-welcome.md

          